
def cara():
    print(          "                        .                       ")
    print(          "                        l'                      ")
    print(          "                       coo.                     ")
    print(          "                      :oooo.                    ")
    print(          "                     ;oooool.                   ")
    print(          "                    ,oooooool.                  ")
    print(          "                   .oooooooool                  ")
    print(          "                  ...;ooooooool.                ")
    print(          "                 'ool:;:looooool.               ")
    print(          "                'oooooooooooooool.              ")
    print(          "               ,oooooooooooooooool.             ")
    print(          "              ;oooooooooooooooooool.            ")
    print(          "             ;oooooooooooooooooooool.           ")
    print(          "            :ooooooool'.  .:ooooooooo.          ")
    print(          "           cooooooooc       'ooooooooo'         ")
    print(          "         .cooooooooo         ,ooooooooo;        ")
    print(          "        .looooooooo:         .ooooooc:;:;       ")
    print(          "       .loooooooooo:         .ooooooool;.       ")
    print(          "      'oooooooooc;,.          ';:loooooool,     ")
    print(          "     ,ooool:,..                    .';looooc    ")
    print(          "    ;ol:'.                              .;col.  ")
    print(          "   ''.                                      .,.  \n ")
    print("   Sistema creado y mantenido por: Alejandro García")
    print("   Fecha de creacion: 15/08/2022")
    print("   Version: 0.1 Alpha")


